---
driver:
  name: vagrant
  customize: 
    clipboard: 'bidirectional'

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.20.3
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mwrock/Windows2016 
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[chefdk_bootstrap::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
