---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: opentable/win-2012r2-standard-amd64-nocm 
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[chefdk_bootstrap::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
