---
driver:
  name: vagrant
  customize: 
    clipboard: 'bidirectional'

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mwrock/Windows2016 
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[chefdk_bootstrap::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
