---
driver:
  name: vagrant
  customize: 
    clipboard: 'bidirectional'

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
<<<<<<< HEAD
  - name: mwrock/Windows2016 
=======
  - name: mwrock/Windows2016
>>>>>>> 2dd72306de5e835b55b795bd0be3ff89dee4963f
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[chefdk_bootstrap::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: secondary
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes: